Issue #64979 : LoopTiling.cpp (mlir::affine)
mcl-csa/llvm-project-public pull request #5
Opened 2023-09-28 04:48 UTC by SwapnilGhanshyala

Lets Take this branch ahead

2023-10-03 06:22 UTC, bondhugula commented
Please add a proper commit summary and paste the same in the PR summary.

2023-10-03 06:24 UTC, bondhugula requested changes
Please add a link to the upstream issue in the commit summary.

2023-10-03 06:24 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/LoopTiling.cpp
> +              "less than or equal to zero. LoopTiling Pass Aborted!");
Emit messages should start in lower case. Avoid referring to the pass name here - it may change later.

2023-10-03 06:24 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Transforms/LoopTiling.cpp
> +    Builder b = Builder(getOperation()->getContext());
Why did you need to create a builder here? Also, just `&getContext()` will work if you need the context.

2023-10-03 06:59 UTC, SwapnilGhanshyala commented
Addressed the 3 comments in the new commit. 
Updated Commit message , added Issue Link and updated Error handling code in LoopTiling.cpp

2023-10-26 10:01 UTC, SwapnilGhanshyala commented
Commit Summary:

Updated LoopTiling::runOnOperation() to signal pass failure incase the
set cachesize is invalid, i.e., less than or equal to zero.

#64979 is the reporting issue.

2024-11-03 23:24 UTC, closed without merging