Issue #64287 : AffineStructures.cpp (mlir::affine)
mcl-csa/llvm-project-public pull request #6
Opened 2023-09-28 05:52 UTC by SwapnilGhanshyala

2023-10-03 06:19 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Analysis/AffineStructures.cpp
> +    if (!((isTopLevelValue(operand)) || (isAffineInductionVar(operand)))) {
Unnecessary parentheses here. Use `!.... && !....`.

2023-10-03 06:22 UTC, bondhugula requested changes
This isn't the right fix.

Also, please update the commit summary to include a link to the issue being addressed by this if that's the case.

2023-10-03 06:22 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Analysis/AffineStructures.cpp
> +          "Aborted!");
Remove unnecessary capitatlization. All emit messages should start in lower case.

"value is neither a top-level value nor an affine IV; non-termnial symbol/loop IV expected; pass aborted"

2023-10-03 06:22 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Analysis/AffineStructures.cpp
> +      return failure();
You can simply do `return emitError(...)` in one line.

2023-10-03 06:22 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Analysis/AffineStructures.cpp
> +          "Aborted!");
Putting an emitError is not the right fix - this method is simply meant to return failure. It's the caller that has to deal with it appropriately.

2023-10-26 09:39 UTC, SwapnilGhanshyala commented
Changes:
1) removed redunc

2023-10-26 09:39 UTC, closed without merging