[MLIR][Affine] Fixed nesting of loops in fusion-maximal (Issue #61820)
mcl-csa/llvm-project-public pull request #9
Opened 2023-12-27 17:29 UTC by SwapnilGhanshyala

When maximal fusion is requested, slice computation can skip checking if the sibling loop is parallel or not, since maximal does not care about performance improvement. Modified slice computation to skip said check if the maximal flag is set. Modified FusionStrategy class to have a boolean member representing maximal fusion and modified slice computation methods to pass the information about the selected strategy.

**Issue**: The Issue we are trying to solve is the unnecessary nesting of loops as a result of maximal fusion #61820
**Original Pipeline**: If the sibling was sequential, then its bounds were set to be constants (the original bounds). This was forcing a nesting of the loops instead of fusion. In standard fusion (non-maximal), the strategy would have been rejected based on performance heuristics, and another iteration of bounds calculation would start. However, in maximal-fusion, this nested strategy would not be rejected.
**Solution**: When in maximal fusion, skip the check on the sibling to see if it is parallel or not.
**Reasoning**: The fusion of parallel to sequential loops will produce sequential loops. It seems to be a performance-based decision to not let this happen. Hence maximal fusion can safely ignore this check.

2024-01-17 10:16 UTC, SwapnilGhanshyala commented
Hi @bondhugula, a gentle reminder for a review.

2024-01-17 10:34 UTC, bondhugula requested changes
The API update isn't proper.

2024-01-17 10:34 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Analysis/Utils.cpp
> +      if (isInnermostInsertion() && srcIsUnitSlice() && isMaximal && *isMaximal)
else if

2024-01-17 10:34 UTC, bondhugula commented on mlir/include/mlir/Dialect/Affine/Analysis/Utils.h
> +                  FusionStrategy fusionStrategy);
This isn't proper to do. `computeSliceUnion` shouldn't have anything to do with the fusion strategy or anything fusion related. You'll have to rethink what option to pass if the behavior has to change here.

2024-01-17 10:34 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Analysis/Utils.cpp
> +      if (isInnermostInsertion() && srcIsUnitSlice() && isMaximal && *isMaximal)
Again this is an analysis utility and should not refer to any specific fusion-related things.

2024-01-17 10:34 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Analysis/Utils.cpp
> +          isInnermostInsertion() && srcIsUnitSlice() && isMaximal && *isMaximal)
For eg., one can add an option `skipParallelismCheck`. 

Lower-level utilities shouldn't refer to or encode any semantics from higher-level/client utilities.

2024-01-23 08:27 UTC, SwapnilGhanshyala commented
I see, this lower-level utility might be used by other mechanisms than loop fusion, and should be agnostic of that. So rather than passing the `fusionStrategy`, just passing a flag/option to skip the parallelism check is more appropriate.

Will make the changes.

2024-01-30 10:07 UTC, SwapnilGhanshyala commented on mlir/include/mlir/Dialect/Affine/Analysis/Utils.h
> +                              bool skipParallelismCheck);
modified signatures of `getComputeSliceState()` and `computeSliceUnion()` to also receive a `bool skipParallismCheck`, which is a flag to skip parallelism check on sibling loop if set.

2024-01-30 10:36 UTC, SwapnilGhanshyala commented on mlir/include/mlir/Dialect/Affine/LoopFusionUtils.h
> +  bool maximalFusion;
modified FusionStrategy class to have member `bool maximalFusion` which represents if fusion-maximal is set or not. Also, added a method that returns it's set value.

2024-01-30 10:53 UTC, SwapnilGhanshyala reviewed
Hi @bondhugula, pushed the changes addressing previous comments. 
Importantly, addressed the comment to make the slice computation agnostic of where it is called from.

2024-01-30 14:08 UTC, bondhugula reviewed
Missing test case!

2024-01-30 14:08 UTC, bondhugula commented on mlir/include/mlir/Dialect/Affine/Analysis/Utils.h
> +/// heuritic can be ignored.
heuristic

2024-01-30 14:08 UTC, bondhugula commented on mlir/include/mlir/Dialect/Affine/Analysis/Utils.h
> +                  bool skipParallelismCheck);
All inputs should appear before. `sliceUnion` is an output arg.

2024-01-30 14:08 UTC, bondhugula commented on mlir/include/mlir/Dialect/Affine/LoopFusionUtils.h
> +  /// Fusion Maximal.
Maximal fusion

2024-01-30 14:08 UTC, bondhugula commented on mlir/lib/Dialect/Affine/Analysis/Utils.cpp
> +    if (skipParallelismCheck) {
Need to add a code comment here.

2024-01-31 08:09 UTC, SwapnilGhanshyala commented on mlir/lib/Dialect/Affine/Analysis/Utils.cpp
> +    if (skipParallelismCheck) {
Done.

2024-01-31 08:10 UTC, SwapnilGhanshyala commented on mlir/test/Dialect/Affine/loop-fusion-4.mlir
> +// RUN: mlir-opt -allow-unregistered-dialect %s -pass-pipeline='builtin.module(func.func(affine-loop-fusion{fusion-maximal}))' -split-input-file | FileCheck %s --check-prefix=FUSION-MAXIMAL
Added unit test.

2024-01-31 08:18 UTC, SwapnilGhanshyala commented
Hi @bondhugula, addressed the comments and added a unit test to loop-fusion-4.mlir.

2024-02-02 08:15 UTC, SwapnilGhanshyala reviewed
Submitted changes w.r.t. previous comments.

2024-02-12 08:50 UTC, SwapnilGhanshyala commented
Hi @bondhugula , gentle reminder for review.

2025-02-23 04:19 UTC, bondhugula requested changes
This isn't the right fix or approach. The incorrect fusion has nothing specific to do with sequential loops or parallel loops nor to do with maximal fusion (it could also happen with non-maximal fusion where the compute tolerance allows sufficient redundant computation) nor specific to reduction. The invalid fusion is due to cyclic dependences in the source nest. This is fixed comprehensively by https://github.com/llvm/llvm-project/pull/128397
It also required a fix to a check on the compute tolerance.

2025-02-23 04:20 UTC, closed without merging